### PR TITLE
#142 Implemented dynamic filtering response

### LINKED ISSUE #142: States/City/Postal/Zip should be filtering based on what is fitlered already
If Canada is selected, than only Canadian Provinces, Cities, and Postals should be shown.

If Canada and Ontario is selected, then only Cities and Postals in Ontario, Canada should be shown.

Etc.

### PR DESCRIPTION
**Pull request by stephenmartin2951**
I left the rate limiting at 5. I was using 500 when testing locally. Not sure if you want to increase it or not and if so, by how much.

### CODE REVIEW

**Comment by kellenwiltshire** [comment]
Sorry, haven't got a chance to look at this yet! Will get to it soon!

**Comment by kellenwiltshire** [comment]
Found an enhancement possibility, if you set all the Filters, such as Canada/Ontario/Toronto and then try to change the country, it should clear the other selections for State, City, and Zip since those selected values would no longer be applicable.

**Comment by stephenmartin2951** [comment]
I like it. I have some family coming to visit tomorrow through the weekend so idk how much work I'll get done through Sunday but I will get that implemented as soon as I am able to.

**Comment by kellenwiltshire** [comment]
Looking good! Found a possible bug though.

If I set the filters Canada/Ontario/Toronto and then I change the Country to USA, it works great to reset the following filters. But then when I set the State, nothing populates for the City section.

**Comment by stephenmartin2951** [comment]
Hmm. When I follow that flow I am seeing the states and cities. Are you getting rate limited?

**Comment by kellenwiltshire** [comment]
Yup, that is what is happening. Let's increase this limit to maybe 20?

**Comment by stephenmartin2951** [comment]
Yeah I didn't do a good job testing that because I am working with a limited database and I wasn't sure if I could find an appropriate limit. 20 is probably a good place to start.

**Review by kellenwiltshire — APPROVED** [review]
Looks Great!

**Pull request merged**
