### PR TITLE
Update review form

### PR DESCRIPTION
**Pull request by kellenwiltshire**

### CODE REVIEW

**Comment by stephenmartin2951** [comment]
Looks really good. I am getting a 401 when posting to /api/review/submit-review. Maybe I'm missing a variable in my .env?

**Comment by stephenmartin2951** [comment]
Switched over to the update-alerts branch and was able to submit a review without issue.

**Comment by kellenwiltshire** [comment]
Hmm... Interesting. I will investigate further. I didn't change any logic with review submitting

**Comment by stephenmartin2951** [comment]
I just switched back and it posted fine. Not sure what the deal was.

**Comment by stephenmartin2951** [comment]
I did notice an error in the console that said "Uncaught (in promise) Timeout" that didn't appear this time. Could be related

**Review by stephenmartin2951 — APPROVED** [review]

**Pull request merged**
