### PR TITLE
feat: add Norway as a selectable country

### PR DESCRIPTION
**Pull request by DevDeb91**
Refs: #163

### CODE REVIEW

**Comment by kellenwiltshire** [comment]
WIll have more time to look at this this weekend!

**Review by kellenwiltshire — APPROVED** [review]
This looks great! Works as expected. Come back to the Discord and we can see about how best to launch this!

**Comment by kellenwiltshire** [comment]
Just need to resolve the conflict that came up. Should just need to run `bun install` again and then commit the changes.

**Comment by kellenwiltshire** [comment]
Can you remove this file - 0001-feat-add-Norway-as-a-selectable-country.patch

**Comment by DevDeb91** [comment]
> Just need to resolve the conflict that came up. Should just need to run `bun install` again and then commit the changes.

Thanks!! 😊🙏

**Review by kellenwiltshire — APPROVED** [review]
Looks Great!

**Comment by DevDeb91** [comment]
Thanks @kellenwiltshire 🙏😄

**Pull request merged**
