### PR TITLE
Add location form to set filtering before displaying reviews

### PR DESCRIPTION
**Pull request by stephenmartin2951**
Also refactored out repeated code, injected selected location into map component, and fixed duplicate cities showing up in dynamic options (fixed in api call not in db)

### CODE REVIEW

**Review by kellenwiltshire — CHANGES_REQUESTED** [review]
Pretty good start I think! 

Couple changes:

1. I think we should still be showing the Ad component on the review page while they pick their location.
2. I think we should remove the City and Postal code from that initial location picking. I think it is too many boxes to go through
3. When a Country and State are not selected, the `continue` button should be disabled. 
4. There is a lot of whitespace on that initial page to pick a location. maybe we can center things a little more and stylize the inputs a bit? They could maybe bit a bit larger too, at least on desktop

Great start though, I think where it is going!

**Comment by stephenmartin2951** [comment]
Thanks for the feedback. I believe my latest commit addresses all 4 items.

**Comment by kellenwiltshire** [comment]
Definitely getting closer! 

Couple more changes I think

- I don't think we need the bottom border separating `continue` , in fact, maybe we can put the whole thing inside the top part so that it matches closer to the Create a Review page starter

image

- I think the inputs should be vertically aligned instead of horizontal. If you're feeling up to it, maybe we add some transition flair where the state selected fades in after you select a country.

- On mobile, there is a little bit of an issue with margins/padding with the screen edge as well

image


This is looking great though! I like where it is heading!

**Comment by kellenwiltshire** [comment]
Don't be mad lol

The formatting is still a little off on Desktop and Mobile. This 
image

Should be more like this:

image

and similar on mobile:
image
image


There is also a weird issue with the country selector on mobile and desktop 
image
image

Otherwise it is really coming together!

**Comment by stephenmartin2951** [comment]
All good lol let's get it right. I'll take a look.

**Comment by stephenmartin2951** [comment]
Is the weird issue you referenced the options getting stuck open?

**Comment by kellenwiltshire** [comment]
> Is the weird issue you referenced the options getting stuck open?

No, it is when the selection box is way outside the bounds on mobile, and outside the box on desktop

**Comment by kellenwiltshire** [comment]
Okay, those changes look a lot better now!

Last issue then, when using the affiliate link `reviews?view=map&affiliate=stfx` it needs to bypass this and just open the map right away to stfx university.

**Comment by stephenmartin2951** [comment]
I think my last commit should address the direct routing.

**Review by kellenwiltshire — APPROVED** [review]

**Pull request merged**
